Feature#8
tsushoji/AutoReportAppProject pull request #11
Opened 2020-10-15 08:38 UTC by tsushoji

以下、項目の確認お願いします。

■日報データ出力
・フォルダパス入力チェック

・出力ファイルパスチェック

・日報データ出力

■週報出力
・フォルダパス入力チェック

・対象管理番号入力チェック

・出力ファイルパスチェック

・日報データ出力

2020-10-15 13:43 UTC, re3assist requested changes
少し細かめにレビューしました。
疑問などありましたまたご連絡ください！

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +        WEEKLYREPORT
細かいですが、
大文字で表現するなら単語の区切りをUPPER_SNAKE_CASEで表現していたほうが良いと思います。
UPPER_SNAKE_CASE自体あまり評判はよくないですが区切り無しでやっているより良いかと思います。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            int controlNum;
forの中で宣言して
```c#
int controlNum = Int32.Parse(keyValuePair.Value.ControlNum);
controlNumList.Add(controlNum);
```
のほうが変数のスコープが狭まるので私は好きです。

以下のようにすると宣言も不要ですが、横に長くなるのでこのアリは好みの問題かもです。
```
`controlNumList.Add(Int32.Parse(keyValuePair.Value.ControlNum));`
```

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +        private static readonly char commaChar = ',';
delimiterとかのほうが適切ですね。
,から|などに区切りを変更した場合、関数名も変えないと整合性があわなくなるので。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //メソッドを抜ける
本当にさじ加減がむずかしいのですが、処理をみたらわかるようなことは書かないほうがよいです。
（コメントを書けと言ったり書くなといったり混乱させてしまいそうですが・・・。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                outputPath = this.textBox2.Text + weeklyReportTxtFileNameWithExt;
特に理由がない場合は、宣言と代入は一緒にしていたほうがすっきりすると思います。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                {
if文のネストはなるべく浅くするほうが可読性が上がります。
```C#
if (File.Exists(outputPath))
{
    // こんな感じで処理を終わらせておくと以降の処理のネストが1段下がるはず。
    MessageBox.Show(Properties.Resources.E0004);
    //「出力フォルダパス」リセット
    this.textBox2.ResetText();
    return;
}
```
私はよく
```C#
// エラーチェック
やりたい処理で使用する値が不正の場合はここで処理を終わらす

// やりたい処理
処理実行（実行時例外などはとりあえずthrow
```
みたいな感じで処理を作る事が多いです。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //「出力フォルダパス」、「対象管理番号」リセット
このコメントをが逐一出てくるということは変数名が良くないと思われます。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    for (int i = 0; i < DataGridView1.Rows.Count - 1; i++)
foreachは使えないでしょうか？

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    string[] strControlNumArray = this.textBox3.Text.Split(commaChar);
ハンガリアン記法は使わなくてよいと思います。
昔のC言語のように処理の先頭で宣言しないといけないなどの成約がないので、
C#などの最近のプログラミング言語でこの記法を使うメリットは少ないと思います。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            this.textBox1.ResetText();
・出力後にパスのクリアをしなくてもよいかと思いました。
　もう一回出力したい。ということもあると思うので。
　また上書き保存の確認後にキャンセルするとパスが消えるのも再選択しないといけないのはちょっと不便かなと思います。
（週報も同じ

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            return rtnFlag;
この処理なら
return errMsg.Length > 0;にすればrtnFlagを作成する必要は無いかと思います。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            if (outputType == OutputType.WEEKLYREPORT)
下に同じIF分があるように見えます。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            if (strArray.Length > 0)
forを使っているのならここで配列の数をチェックする意味はありません。
forはLength が0の場合は一回も回らず処理を終了するため。

2020-10-15 13:43 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                            break;
return false;
にするとrtnFlagはいらないと思います。

2020-10-15 14:00 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +        WEEKLYREPORT
上記承知いたしました。
修正いたします。

2020-10-15 14:11 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +        private static readonly char commaChar = ',';
上記承知いたしました。
修正いたします。

2020-10-15 14:12 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                outputPath = this.textBox2.Text + weeklyReportTxtFileNameWithExt;
上記、承知いたしました。
修正いたします。

2020-10-15 14:32 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            int controlNum;
for文の外で値型変数を宣言することで、変数を使いまわせるかと考え外で宣言いたしました。
このぐらいのメモリー確保であれば、変数のスコープが狭まることを優先し、for文の中で宣言した方がよろしいのでしょうか。

2020-10-15 14:35 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //メソッドを抜ける
上記、承知いたしました。
一回自分で全体確認し、修正いたします。

2020-10-15 14:52 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            return rtnFlag;
上記、承知いたしました。
修正いたします。

2020-10-15 15:09 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                            break;
上記、承知いたしました。
一回修正いたします。

2020-10-15 15:11 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            if (strArray.Length > 0)
上記、承知いたしました。
修正いたします。

2020-10-15 15:35 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            if (outputType == OutputType.WEEKLYREPORT)
以下の場合、対象管理番号項目の形式チェックとしたいと考えていたため、このようなロジックになりました。
上記、実装より適切なロジックご存じでしたら、ご教授いただけないでしょうか。
・「outputType」が「OutputType.WEEKLY_REPORT」のとき
・「対象管理番号」が「null」または「空白」でないとき

2020-10-15 15:37 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            this.textBox1.ResetText();
ユーザー目線で考えると、アドバイスいただいたことが適切であると考えました。
修正いたします。

2020-10-15 23:33 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            int controlNum;
そうですね。
for外で宣言していたほうがメモリの使用率は下がるというのはそのとおりかと思いますが、メモリの使用についてそれほどシビアでないシステムにおいてはスコープのほうを意識するほうがよいと私は思っています。（諸説あると思いますが。。。）

イメージは以下の記事の感じですね。
https://qiita.com/mtanabe/items/062647322987901f5237

2020-10-15 23:50 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            if (outputType == OutputType.WEEKLYREPORT)
コメントしたつもりでしたが漏れていたいようです。
Inputcheckメソッドの役割が多すぎるのが良くないなのかなと思います。
`validatedaylyReport`
`validateWeeklyReport`

みたいに分割すれば、IF文自体を書かなくて良いかと。

2020-10-18 12:28 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            int controlNum;
上記、承知いたしました。
修正いたします。

2020-10-18 13:00 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                {
「if (System.IO.Directory.Exists(this.textBox1.Text))」、「if (System.IO.Directory.Exists(this.textBox2.Text))」の条件部分で認識あってますでしょうか。

2020-10-18 13:03 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    for (int i = 0; i < DataGridView1.Rows.Count - 1; i++)
インデックス番号「DataGridView1.Rows.Count - 1」を常に回したくなかったため、for文に実装いたしました。
foreach文で回し、中のif文でインデックス番号が「DataGridView1.Rows.Count - 1」のときはじく実装にした方がよろしかったでしょうか。

2020-10-18 13:04 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //「出力フォルダパス」、「対象管理番号」リセット
どの変数名のことを指してますでしょうか。

2020-10-18 13:19 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    string[] strControlNumArray = this.textBox3.Text.Split(commaChar);
上記、承知いたしました。
一回、修正いたします。

2020-10-18 13:31 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    string[] strControlNumArray = this.textBox3.Text.Split(commaChar);
ハンガリアン記法について、以下はハンガリアン記法でないという認識でよろしかったでしょうか。
（変数の型ではなく、英訳上型名と同じ単語があるもの）
・winCharCode
・repFthStr

2020-10-18 14:24 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +            if (outputType == OutputType.WEEKLYREPORT)
上記、承知いたしました。
一回修正してみます。

2020-10-19 11:24 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                {
はい、上記の箇所であっています。

2020-10-19 11:27 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //「出力フォルダパス」、「対象管理番号」リセット
範囲指定が出来ていませんでした。
変数ではなくコントロールの名前ですね。
this.textBox2.ResetText();
this.textBox3.ResetText();

2020-10-19 11:30 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    string[] strControlNumArray = this.textBox3.Text.Split(commaChar);
はい。そうですね。
ハンガリアン記法は変数の型が変数からわかるようにするみたいな感じだったと思います。（私の認識だと
なので、winはwindows、repはreplaceの単語の略語だと思うのでハンガリアン記法ではないと思っています。

2020-10-19 12:08 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    string[] strControlNumArray = this.textBox3.Text.Split(commaChar);
あ、ごめんなさい。
ちなみにコントール名はハンガリアン記法でつける。
という意見もありますので、そのあたりは自分のわかりやすいほうでつけてみると良いかと思います。
（私もコントロール名をハンガリアンでつけるのは賛成派です（あまり.NETを使ったことがない人間ですが、、、。

2020-10-19 12:25 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    for (int i = 0; i < DataGridView1.Rows.Count - 1; i++)
いえ、失礼しました。
データグリッドの最終行が空行だからそれを回したくないのですね。見れていませんでした。
それなら上記の書き方でも良いと思います！

ただDataGridView1.Rows[i]が名前が長いので、以下のように変数にとっておくとあとの処理がすっきりすると思います。
```c#
var row = DataGridView1.Rows[i];
```

ちなみにもし私が書くならこんな感じかなと思いました。
```c#
// ★dataGridView1がDailyReportGridViewとかならrowでよいかと。
foreach (var row in DataGridView1.Rows.Cast<DataGridViewRow>())
{
    // ★strControlNumArrayがoutputTargetControlNumberListになってるともっとわかりよいかなと思ったりします。
    if (row.Cells[0].Value != null && strControlNumArray.Contains(row.Cells[0].Value.ToString()))
    {
        var reportData = new DailyReportEntity();
        reportData.ControlNum = row.Cells[0].Value.ToString();
        reportData.DateStr = row.Cells[1].Value.ToString();
        reportData.ImplementationContent = row.Cells[2].Value.ToString();
        reportData.TomorrowPlan = row.Cells[3].Value.ToString();
        reportData.Task = row.Cells[4].Value.ToString();
        outputWeeklyReportDataList.Add(reportData);
    }
}
```

上記の★ように変数名を変えているとコメントがなくてもこのコードをみると
>データグリッドから管理番号に一致する行のデータをoutputWeeklyReportDataListに追加

から

>日報データグリッドから出力対象の管理番号に一致する行のデータをoutputWeeklyReportDataListに追加

のように情報量が多くなるのでこういうことを意識してつくるようにしています。
また見通しを良くすることでコードを読むスピードもあがるのかなと思いっています。

2020-10-19 15:21 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                {
上記、承知いたしました。
一回修正いたします。

2020-10-19 15:22 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    string[] strControlNumArray = this.textBox3.Text.Split(commaChar);
上記、承知いたしました。
一回「変数の型が変数からわかるようにしていないか」という観点で変数名修正いたします。

2020-10-19 15:44 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                    for (int i = 0; i < DataGridView1.Rows.Count - 1; i++)
上記、ご教授ありがとうございます。
上記を参考にし、データグリッドビューの値取得の処理実装していきます。

2020-10-19 15:48 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //「出力フォルダパス」、「対象管理番号」リセット
上記テキストボックス名も考えて命名した方がよいという認識でよろしいでしょうか。
もし、コントロール名を変更する場合、ソースコードで使用するコントローラ名はすべて命名した方がベストでしょうか。

2020-10-19 23:50 UTC, re3assist commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //「出力フォルダパス」、「対象管理番号」リセット
そうですね。私は変えていたほうが良いかなと思っています。
（この規模のツールの開発でそこまでやるのかという話はおいておいて。）

練習を兼ねていると思うので一度つけてみましょう。

コントロールの命名についてのベストプラクティス的なものを見つけられませんでした。
なのでコントロール名の付け方にはいろいろな意見があるようです。
（参考：https://qiita.com/Ted-HM/items/67eddbe36b88bf2d441d のコントロールのフィールド(※変更)を参照）

で結論ですが、項目名＋コントロール文言　みたいな感じでつければ良いかなと思います。（ユーザ名であればuserNameTextBox など）

2020-10-21 06:25 UTC, tsushoji commented on AutoReportWinApp/DailyReportDataListForm.cs
> +                        //「出力フォルダパス」、「対象管理番号」リセット
上記のご指摘点について、今回はメッセージさせていただいたように修正不要とさせていただきます。

2020-10-21 09:01 UTC, closed without merging